Remove all Scss
  anythign related to Sass was giving the flowing error on build.

  ERROR: execute of template failed: template: partials/head.html:45:70: executing "partials/head.html" at <resources>: can't evaluate field Sass in type interface {}

  not sure what the sass provides for me here so it have been removed
  for now.